"""create_medlens_normalized_tables

Revision ID: 723372a226af
Revises: 
Create Date: 2026-09-05 11:14:29.383462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '723372a226af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('patients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mrn', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.String(length=10), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=20), nullable=False),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_synthetic_demo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_mrn'), ['mrn'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('verification_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('verified_by', sa.String(length=100), nullable=True),
    sa.Column('original_value', sa.String(length=200), nullable=True),
    sa.Column('corrected_value', sa.String(length=200), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('provenance', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conflicts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('conflict_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_a', sa.Text(), nullable=True),
    sa.Column('source_b', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256_checksum', sa.String(length=64), nullable=False),
    sa.Column('report_date', sa.String(length=20), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('facility', sa.String(length=200), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index('idx_documents_patient_status', ['patient_id', 'processing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_processing_status'), ['processing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_sha256_checksum'), ['sha256_checksum'], unique=False)

    op.create_table('patient_allergies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('allergen', sa.String(length=200), nullable=False),
    sa.Column('reaction', sa.String(length=200), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('provenance', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_conditions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('condition_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('diagnosed_date', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('provenance', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_medications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('medication_name', sa.String(length=200), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('route', sa.String(length=50), nullable=True),
    sa.Column('provenance', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_symptoms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('symptom', sa.String(length=200), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('provenance', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.Column('model_provider', sa.String(length=50), nullable=True),
    sa.Column('provenance', sa.String(length=50), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_summaries_patient_id'), ['patient_id'], unique=False)

    op.create_table('document_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_pages_document_id'), ['document_id'], unique=False)

    op.create_table('document_processing_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('log_messages', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_processing_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_processing_jobs_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_processing_jobs_status'), ['status'], unique=False)

    op.create_table('extracted_entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('source_evidence', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('provenance', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extracted_entities', schema=None) as batch_op:
        batch_op.create_index('idx_extracted_entities_patient_type', ['patient_id', 'entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_entities_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_entities_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_entities_patient_id'), ['patient_id'], unique=False)

    op.create_table('lab_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('test_name', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('value_text', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('raw_reference_range', sa.String(length=200), nullable=True),
    sa.Column('reference_low', sa.Float(), nullable=True),
    sa.Column('reference_high', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_evidence', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.Column('provenance', sa.String(length=50), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.String(length=100), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('original_ai_value', sa.String(length=100), nullable=True),
    sa.Column('original_ai_unit', sa.String(length=50), nullable=True),
    sa.Column('original_ai_range', sa.String(length=200), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('report_date', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.create_index('idx_lab_results_patient_status', ['patient_id', 'status'], unique=False)
        batch_op.create_index('idx_lab_results_patient_test', ['patient_id', 'test_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_results_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_results_is_verified'), ['is_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_results_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_results_provenance'), ['provenance'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_results_report_date'), ['report_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_results_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_results_test_name'), ['test_name'], unique=False)

    op.create_table('observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_evidence', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('provenance', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observations_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_patient_id'), ['patient_id'], unique=False)

    op.create_table('review_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('current_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reference_ranges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lab_result_id', sa.String(length=36), nullable=False),
    sa.Column('raw_text', sa.String(length=200), nullable=True),
    sa.Column('low_value', sa.Float(), nullable=True),
    sa.Column('high_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('is_assessable', sa.Boolean(), nullable=False),
    sa.Column('source_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lab_result_id'], ['lab_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reference_ranges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reference_ranges_lab_result_id'), ['lab_result_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reference_ranges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reference_ranges_lab_result_id'))

    op.drop_table('reference_ranges')
    op.drop_table('review_items')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_patient_id'))
        batch_op.drop_index(batch_op.f('ix_observations_document_id'))

    op.drop_table('observations')
    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_results_test_name'))
        batch_op.drop_index(batch_op.f('ix_lab_results_status'))
        batch_op.drop_index(batch_op.f('ix_lab_results_report_date'))
        batch_op.drop_index(batch_op.f('ix_lab_results_provenance'))
        batch_op.drop_index(batch_op.f('ix_lab_results_patient_id'))
        batch_op.drop_index(batch_op.f('ix_lab_results_is_verified'))
        batch_op.drop_index(batch_op.f('ix_lab_results_document_id'))
        batch_op.drop_index('idx_lab_results_patient_test')
        batch_op.drop_index('idx_lab_results_patient_status')

    op.drop_table('lab_results')
    with op.batch_alter_table('extracted_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extracted_entities_patient_id'))
        batch_op.drop_index(batch_op.f('ix_extracted_entities_entity_type'))
        batch_op.drop_index(batch_op.f('ix_extracted_entities_document_id'))
        batch_op.drop_index('idx_extracted_entities_patient_type')

    op.drop_table('extracted_entities')
    with op.batch_alter_table('document_processing_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_processing_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_document_processing_jobs_document_id'))

    op.drop_table('document_processing_jobs')
    with op.batch_alter_table('document_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_pages_document_id'))

    op.drop_table('document_pages')
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_summaries_patient_id'))

    op.drop_table('summaries')
    op.drop_table('patient_symptoms')
    op.drop_table('patient_medications')
    op.drop_table('patient_conditions')
    op.drop_table('patient_allergies')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_sha256_checksum'))
        batch_op.drop_index(batch_op.f('ix_documents_processing_status'))
        batch_op.drop_index(batch_op.f('ix_documents_patient_id'))
        batch_op.drop_index('idx_documents_patient_status')

    op.drop_table('documents')
    op.drop_table('conflicts')
    op.drop_table('verification_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_mrn'))

    op.drop_table('patients')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
