"""add_relevant_history_and_is_archived_to_patients

Revision ID: cf2f25731c9f
Revises: 723372a226af
Create Date: 2026-09-05 11:18:50.996551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf2f25731c9f'
down_revision: Union[str, Sequence[str], None] = '723372a226af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relevant_history', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_patients_is_archived'), ['is_archived'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_is_archived'))
        batch_op.drop_column('is_archived')
        batch_op.drop_column('relevant_history')

    # ### end Alembic commands ###
