"""
Strict Clinical Extraction Schemas
===================================
Defines the canonical data models for all AI-extracted clinical entities.
Every extracted field carries:
  - provenance  : AI_EXTRACTED | USER_PROVIDED | HUMAN_VERIFIED
  - confidence  : float 0.0 – 1.0
  - source_evidence: verbatim quote from the source document
  - document_id : which document produced this entity
  - page_number : which page (1-indexed), None if not applicable

CRITICAL SAFETY RULE:
  reference_range_text MUST be a verbatim quote extracted directly from the
  source document text. Any reference range not grounded in source text MUST
  be left as None. The business validator enforces this; the schema declares
  the contract.
"""

from __future__ import annotations

from enum import Enum
from typing import List, Literal, Optional, Union

from pydantic import BaseModel, Field, field_validator, model_validator


# ---------------------------------------------------------------------------
# Provenance enumeration
# ---------------------------------------------------------------------------

class Provenance(str, Enum):
    """Tracks the origin and review status of every clinical data element."""
    AI_EXTRACTED   = "AI_EXTRACTED"    # Generated by the AI extraction pipeline
    USER_PROVIDED  = "USER_PROVIDED"   # Manually entered by a clinician
    HUMAN_VERIFIED = "HUMAN_VERIFIED"  # AI-extracted and reviewed/confirmed by a clinician


class ExtractionStatus(str, Enum):
    """Normalised evaluation status for numeric lab values."""
    LOW     = "LOW"
    NORMAL  = "NORMAL"
    HIGH    = "HIGH"
    UNKNOWN = "UNKNOWN"  # Missing range or non-numeric value — never inferred


# ---------------------------------------------------------------------------
# Shared provenance mixin
# ---------------------------------------------------------------------------

class ProvenanceMixin(BaseModel):
    """Fields required on every extracted clinical entity."""
    provenance: Provenance = Provenance.AI_EXTRACTED
    confidence: float = Field(
        default=0.85,
        ge=0.0,
        le=1.0,
        description="Model confidence in this extraction (0.0–1.0)."
    )
    source_evidence: Optional[str] = Field(
        default=None,
        description=(
            "Verbatim quote from the source document that supports this extraction. "
            "Must appear in the document text. Required for grounding validation."
        )
    )
    document_id: Optional[str] = Field(
        default=None,
        description="UUID of the source document."
    )
    page_number: Optional[int] = Field(
        default=None,
        ge=1,
        description="1-indexed page number where the entity was found."
    )

    @field_validator("confidence")
    @classmethod
    def validate_confidence(cls, v: float) -> float:
        return round(v, 4)


# ---------------------------------------------------------------------------
# Lab Result (most complex entity — strict reference range rules)
# ---------------------------------------------------------------------------

class ExtractedLabResult(ProvenanceMixin):
    """
    A single discrete laboratory test result extracted from a medical report.

    CRITICAL reference range rule:
      reference_range_text MUST be copied verbatim from the document.
      If the document does not provide a range, both reference_range_text and
      status must be None/UNKNOWN respectively. The AI must NOT infer ranges
      from clinical knowledge.
    """
    test_name: str = Field(..., min_length=1, max_length=200)
    value: Optional[float] = Field(
        default=None,
        description="Numeric value if the result is quantitative."
    )
    value_text: str = Field(
        ...,
        min_length=1,
        max_length=100,
        description="Raw result text as it appears in the document (e.g. '12.5', 'Positive', 'Trace')."
    )
    unit: Optional[str] = Field(
        default=None,
        max_length=50,
        description="Unit of measurement (e.g. 'g/dL', 'mmol/L')."
    )
    reference_range_text: Optional[str] = Field(
        default=None,
        max_length=200,
        description=(
            "VERBATIM reference range as it appears in the source document. "
            "MUST be None if the document does not provide a range. "
            "Do NOT invent, infer, or fill from medical knowledge."
        )
    )
    status: ExtractionStatus = Field(
        default=ExtractionStatus.UNKNOWN,
        description=(
            "Evaluation against the documented reference range. "
            "MUST be UNKNOWN if reference_range_text is None."
        )
    )
    report_date: Optional[str] = Field(
        default=None,
        description="ISO date YYYY-MM-DD of the report, if present in the document."
    )

    @model_validator(mode="after")
    def enforce_reference_range_safety(self) -> "ExtractedLabResult":
        """
        CRITICAL SAFETY VALIDATOR:
        If reference_range_text is None or empty, status MUST be UNKNOWN.
        This prevents the AI from silently asserting LOW/HIGH/NORMAL without
        a document-sourced reference range.
        """
        if not self.reference_range_text or not self.reference_range_text.strip():
            self.reference_range_text = None
            self.status = ExtractionStatus.UNKNOWN
        return self

    @field_validator("report_date")
    @classmethod
    def validate_date_format(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        import re
        if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", v):
            raise ValueError(
                f"report_date must be in YYYY-MM-DD format, got: {v!r}"
            )
        return v


# ---------------------------------------------------------------------------
# Observation
# ---------------------------------------------------------------------------

class ExtractedObservation(ProvenanceMixin):
    """A free-text clinical observation from the report."""
    category: str = Field(
        default="GENERAL",
        description="Category: GENERAL, IMPRESSION, RECOMMENDATION, HISTORY, PHYSICAL_EXAM, etc."
    )
    content: str = Field(..., min_length=1)


# ---------------------------------------------------------------------------
# Symptom
# ---------------------------------------------------------------------------

class ExtractedSymptom(ProvenanceMixin):
    """A reported symptom extracted from document text."""
    symptom: str = Field(..., min_length=1, max_length=200)
    duration: Optional[str] = Field(default=None, max_length=100)
    severity: Optional[str] = Field(default=None, max_length=50)


# ---------------------------------------------------------------------------
# Condition
# ---------------------------------------------------------------------------

class ExtractedCondition(ProvenanceMixin):
    """A medical condition or diagnosis mentioned in the document."""
    condition_name: str = Field(..., min_length=1, max_length=200)
    icd10_code: Optional[str] = Field(default=None, max_length=20)
    status: Optional[str] = Field(
        default=None,
        description="ACTIVE, RESOLVED, CHRONIC, SUSPECTED, HISTORICAL"
    )


# ---------------------------------------------------------------------------
# Medication
# ---------------------------------------------------------------------------

class ExtractedMedication(ProvenanceMixin):
    """A medication mentioned in the document."""
    medication_name: str = Field(..., min_length=1, max_length=200)
    dosage: Optional[str] = Field(default=None, max_length=100)
    frequency: Optional[str] = Field(default=None, max_length=100)
    route: Optional[str] = Field(default=None, max_length=50)


# ---------------------------------------------------------------------------
# Allergy
# ---------------------------------------------------------------------------

class ExtractedAllergy(ProvenanceMixin):
    """An allergy or adverse drug reaction mentioned in the document."""
    allergen: str = Field(..., min_length=1, max_length=200)
    reaction: Optional[str] = Field(default=None, max_length=200)
    severity: Optional[str] = Field(
        default=None,
        description="MILD, MODERATE, SEVERE, LIFE_THREATENING"
    )


# ---------------------------------------------------------------------------
# Master extraction payload
# ---------------------------------------------------------------------------

class ClinicalExtractionPayload(BaseModel):
    """
    Complete structured output from one AI extraction run against a document.
    This is the single object that flows through the validation pipeline.
    """
    document_id: str = Field(..., min_length=1, description="UUID of the source document.")
    provider_name: str = Field(
        description="Name of the AI provider that produced this payload (e.g. 'gemini-1.5-flash', 'mock')."
    )
    report_date: Optional[str] = Field(
        default=None,
        description="Report-level date YYYY-MM-DD if detected at document level."
    )
    lab_results: List[ExtractedLabResult] = Field(default_factory=list)
    observations: List[ExtractedObservation] = Field(default_factory=list)
    symptoms: List[ExtractedSymptom] = Field(default_factory=list)
    conditions: List[ExtractedCondition] = Field(default_factory=list)
    medications: List[ExtractedMedication] = Field(default_factory=list)
    allergies: List[ExtractedAllergy] = Field(default_factory=list)

    # Processing metadata
    extraction_warnings: List[str] = Field(
        default_factory=list,
        description="Non-fatal warnings from the extraction or validation process."
    )
    raw_response: Optional[str] = Field(
        default=None,
        description="Raw AI response string for audit/debugging, not persisted to production DB."
    )

    @field_validator("report_date")
    @classmethod
    def validate_report_date(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        import re
        if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", v):
            raise ValueError(f"report_date must be YYYY-MM-DD, got: {v!r}")
        return v
